"""Record Tablosu

Revision ID: d584fdc977df
Revises: 28cf5124e6e4
Create Date: 2022-01-30 09:50:48.611922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd584fdc977df'
down_revision = '28cf5124e6e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rec_type', sa.Integer(), nullable=False),
    sa.Column('rec_time', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_records_rec_time'), 'customer_records', ['rec_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_records_rec_time'), table_name='customer_records')
    op.drop_table('customer_records')
    # ### end Alembic commands ###
