"""Customer and Record Table

Revision ID: 5abe806560d3
Revises: 
Create Date: 2022-01-30 09:53:15.488163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abe806560d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=False),
    sa.Column('account_no_hash', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_no_hash'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('surname')
    )
    op.create_table('customer_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rec_type', sa.Integer(), nullable=False),
    sa.Column('rec_time', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_records_rec_time'), 'customer_records', ['rec_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_records_rec_time'), table_name='customer_records')
    op.drop_table('customer_records')
    op.drop_table('customer')
    # ### end Alembic commands ###
