"""customer table

Revision ID: 75d98d57a2b5
Revises: 1b02e8cc648c
Create Date: 2022-01-30 09:34:12.840414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d98d57a2b5'
down_revision = '1b02e8cc648c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('birth_date', sa.DateTime(), nullable=False))
    op.add_column('customer', sa.Column('phone_number', sa.String(length=11), nullable=False))
    op.add_column('customer', sa.Column('accountNo_hash', sa.Integer(), nullable=False))
    op.alter_column('customer', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customer', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customer', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'customer', ['phone_number'])
    op.create_unique_constraint(None, 'customer', ['accountNo_hash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='unique')
    op.drop_constraint(None, 'customer', type_='unique')
    op.alter_column('customer', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customer', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customer', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('customer', 'accountNo_hash')
    op.drop_column('customer', 'phone_number')
    op.drop_column('customer', 'birth_date')
    # ### end Alembic commands ###
