"""müşteri tablosu

Revision ID: 6374793fce65
Revises: 
Create Date: 2022-01-30 09:33:39.184670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6374793fce65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musteri',
    sa.Column('musteri_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('surname', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('addres', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('musteri_id')
    )
    op.create_index(op.f('ix_musteri_addres'), 'musteri', ['addres'], unique=True)
    op.create_index(op.f('ix_musteri_email'), 'musteri', ['email'], unique=True)
    op.create_index(op.f('ix_musteri_name'), 'musteri', ['name'], unique=True)
    op.create_index(op.f('ix_musteri_surname'), 'musteri', ['surname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_musteri_surname'), table_name='musteri')
    op.drop_index(op.f('ix_musteri_name'), table_name='musteri')
    op.drop_index(op.f('ix_musteri_email'), table_name='musteri')
    op.drop_index(op.f('ix_musteri_addres'), table_name='musteri')
    op.drop_table('musteri')
    # ### end Alembic commands ###
